name: build sleepytan standalone

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: '1.60.0'
        target: ${{matrix.target}}
        override: true
    - uses: Swatinem/rust-cache@v1
    - uses: actions-rs/cargo@v1
      with:
        command: install
        args: sqlx-cli
    # init db & migrate up
    - uses: actions-rs/cargo@v1
      with:
        command: sqlx
        args: database setup
      env:
        DATABASE_URL: "sqlite://app.db"
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
      env:
        DATABASE_URL: "sqlite://app.db"
    - uses: actions/upload-artifact@v2
      with:
        name: sleepytan-${{matrix.target}}
        path: target/release/sleepytan
